/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author migue
 */
public class RegistroCitaVista extends javax.swing.JFrame {

    public JLabel getAdoctor() {
        return Adoctor;
    }

    public JLabel getAfecha() {
        return Afecha;
    }

    public JLabel getAid() {
        return Aid;
    }

    public JLabel getAmotivo() {
        return Amotivo;
    }

    public JButton getBregistrar() {
        return Bregistrar;
    }

    public JButton getBsalir() {
        return Bsalir;
    }

    public JTextField getTanio() {
        return Tanio;
    }

    public JTextField getTdia() {
        return Tdia;
    }

    public JTextField getTdoctor() {
        return Tdoctor;
    }

    public JTextField getTid() {
        return Tid;
    }

    public JTextField getTmes() {
        return Tmes;
    }

    public JTextField getTmotivo() {
        return Tmotivo;
    }

    public void setAexito(JLabel Aexito) {
        this.Aexito = Aexito;
    }

    public JLabel getAexito() {
        return Aexito;
    }

    public void setAdoctor(JLabel Adoctor) {
        this.Adoctor = Adoctor;
    }

    public JButton getBlimpiar() {
        return Blimpiar;
    }

    public void setAfecha(JLabel Afecha) {
        this.Afecha = Afecha;
    }

    public void setAid(JLabel Aid) {
        this.Aid = Aid;
    }

    public void setAmotivo(JLabel Amotivo) {
        this.Amotivo = Amotivo;
    }

    public void setBlimpiar(JButton Blimpiar) {
        this.Blimpiar = Blimpiar;
    }

    public void setBregistrar(JButton Bregistrar) {
        this.Bregistrar = Bregistrar;
    }

    public void setBsalir(JButton Bsalir) {
        this.Bsalir = Bsalir;
    }

    public void setTanio(JTextField Tanio) {
        this.Tanio = Tanio;
    }

    public void setTdia(JTextField Tdia) {
        this.Tdia = Tdia;
    }

    public void setTdoctor(JTextField Tdoctor) {
        this.Tdoctor = Tdoctor;
    }

    public void setTid(JTextField Tid) {
        this.Tid = Tid;
    }

    public void setTmes(JTextField Tmes) {
        this.Tmes = Tmes;
    }

    public void setTmotivo(JTextField Tmotivo) {
        this.Tmotivo = Tmotivo;
    }

    /**
     * Creates new form RegistroCitaVista
     */
    public RegistroCitaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tdia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tmes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tanio = new javax.swing.JTextField();
        Tmotivo = new javax.swing.JTextField();
        Tdoctor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tid = new javax.swing.JTextField();
        Bsalir = new javax.swing.JButton();
        Bregistrar = new javax.swing.JButton();
        Blimpiar = new javax.swing.JButton();
        Amotivo = new javax.swing.JLabel();
        Adoctor = new javax.swing.JLabel();
        Afecha = new javax.swing.JLabel();
        Aid = new javax.swing.JLabel();
        Aexito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Motivo de connsulta");

        jLabel2.setText("Doctor que atendera");

        jLabel3.setText("Dia");

        jLabel4.setText("Mes");

        jLabel5.setText("Año");

        jLabel6.setText("ID de la mascota");

        Bsalir.setText("Salir");

        Bregistrar.setText("Registrar consulta");

        Blimpiar.setText("Limpiar");

        Amotivo.setForeground(new java.awt.Color(255, 0, 0));
        Amotivo.setText("Campo vacio");
        Amotivo.setEnabled(false);

        Adoctor.setForeground(new java.awt.Color(255, 0, 0));
        Adoctor.setText("Campo vacio");
        Adoctor.setEnabled(false);

        Afecha.setForeground(new java.awt.Color(255, 0, 0));
        Afecha.setText("Fecha incorrecta");
        Afecha.setEnabled(false);

        Aid.setForeground(new java.awt.Color(255, 0, 0));
        Aid.setText("ID incorrecta");
        Aid.setEnabled(false);

        Aexito.setForeground(new java.awt.Color(0, 255, 0));
        Aexito.setText("Registro exitoso");
        Aexito.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Tmotivo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(Tdoctor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tdia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Tmes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Tanio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Amotivo)
                            .addComponent(Adoctor)
                            .addComponent(Afecha)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bsalir)
                        .addGap(18, 18, 18)
                        .addComponent(Bregistrar)
                        .addGap(18, 18, 18)
                        .addComponent(Blimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Aid)
                        .addGap(18, 18, 18)
                        .addComponent(Aexito)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amotivo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tdoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adoctor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Tmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Tanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Afecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aid)
                    .addComponent(Aexito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bsalir)
                    .addComponent(Bregistrar)
                    .addComponent(Blimpiar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCitaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCitaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCitaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCitaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCitaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adoctor;
    private javax.swing.JLabel Aexito;
    private javax.swing.JLabel Afecha;
    private javax.swing.JLabel Aid;
    private javax.swing.JLabel Amotivo;
    private javax.swing.JButton Blimpiar;
    private javax.swing.JButton Bregistrar;
    private javax.swing.JButton Bsalir;
    private javax.swing.JTextField Tanio;
    private javax.swing.JTextField Tdia;
    private javax.swing.JTextField Tdoctor;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tmes;
    private javax.swing.JTextField Tmotivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
